const character = {
	"x": -1166.3100928140552,
	"y": 478.627440332755,
	"note": "This is a proxy object, the real character is in parent.character",
	"properties": [
		"x",
		"y",
		"_events",
		"_eventsCount",
		"tempDisplayObjectParent",
		"transform",
		"alpha",
		"visible",
		"renderable",
		"parent",
		"worldAlpha",
		"filterArea",
		"_filters",
		"_enabledFilters",
		"_bounds",
		"_boundsID",
		"_lastBoundsID",
		"_boundsRect",
		"_localBoundsRect",
		"_mask",
		"_destroyed",
		"children",
		"_anchor",
		"_texture",
		"_width",
		"_height",
		"_tint",
		"_tintRGB",
		"blendMode",
		"shader",
		"cachedTint",
		"_textureID",
		"_textureTrimmedID",
		"vertexData",
		"vertexTrimmedData",
		"_transformID",
		"_transformTrimmedID",
		"pluginName",
		"roundPixels",
		"cskin",
		"i",
		"j",
		"skin",
		"stype",
		"updates",
		"cscale",
		"in",
		"map",
		"hp",
		"max_hp",
		"mp",
		"max_mp",
		"xp",
		"attack",
		"heal",
		"frequency",
		"speed",
		"range",
		"armor",
		"resistance",
		"level",
		"rip",
		"afk",
		"s",
		"c",
		"q",
		"age",
		"pdps",
		"id",
		"cid",
		"cx",
		"slots",
		"ctype",
		"owner",
		"int",
		"str",
		"dex",
		"vit",
		"for",
		"mp_cost",
		"mp_reduction",
		"max_xp",
		"goldm",
		"xpm",
		"luckm",
		"isize",
		"esize",
		"gold",
		"cash",
		"targets",
		"m",
		"evasion",
		"miss",
		"reflection",
		"lifesteal",
		"manasteal",
		"rpiercing",
		"apiercing",
		"crit",
		"critdamage",
		"dreturn",
		"tax",
		"xrange",
		"pnresistance",
		"firesistance",
		"fzresistance",
		"phresistance",
		"stresistance",
		"incdmgamp",
		"stun",
		"blast",
		"explosion",
		"courage",
		"mcourage",
		"pcourage",
		"fear",
		"items",
		"cc",
		"ipass",
		"home",
		"friends",
		"acx",
		"xcx",
		"emx",
		"pzazz",
		"last_ms",
		"cxc",
		"name",
		"displayGroup",
		"parentGroup",
		"walking",
		"animations",
		"fx",
		"emblems",
		"real_alpha",
		"real_x",
		"real_y",
		"type",
		"me",
		"base",
		"awidth",
		"aheight",
		"explanation",
		"ping",
		"vision",
		"ntag_cache",
		"name_tag",
		"last_fear",
		"_activeParentLayer",
		"updateOrder",
		"zOrder",
		"displayOrder",
		"stats",
		"bank",
		"_onTextureUpdate",
		"_onAnchorUpdate",
		"calculateVertices",
		"calculateTrimmedVertices",
		"_renderWebGL",
		"_renderCanvas",
		"_calculateBounds",
		"getLocalBounds",
		"containsPoint",
		"destroy",
		"setTexture",
		"onChildrenChange",
		"addChild",
		"addChildAt",
		"swapChildren",
		"getChildIndex",
		"setChildIndex",
		"getChildAt",
		"removeChild",
		"removeChildAt",
		"removeChildren",
		"updateTransform",
		"calculateBounds",
		"renderWebGL",
		"renderAdvancedWebGL",
		"renderCanvas",
		"containerUpdateTransform",
		"getChildByName",
		"containerRenderWebGL",
		"containerRenderCanvas",
		"_recursivePostUpdateTransform",
		"getBounds",
		"toGlobal",
		"toLocal",
		"setParent",
		"setTransform",
		"displayObjectUpdateTransform",
		"_cacheAsBitmap",
		"_cacheData",
		"_renderCachedWebGL",
		"_initCachedDisplayObject",
		"_renderCachedCanvas",
		"_initCachedDisplayObjectCanvas",
		"_calculateCachedBounds",
		"_getCachedLocalBounds",
		"_destroyCachedDisplayObject",
		"_cacheAsBitmapDestroy",
		"getGlobalPosition",
		"accessible",
		"accessibleTitle",
		"accessibleHint",
		"tabIndex",
		"_accessibleActive",
		"_accessibleDiv",
		"interactive",
		"interactiveChildren",
		"hitArea",
		"buttonMode",
		"cursor",
		"trackedPointers",
		"_trackedPointers",
		"generateTexture",
		"parentLayer",
		"zIndex",
		"layerableChildren",
		"eventNames",
		"listeners",
		"emit",
		"on",
		"once",
		"removeListener",
		"removeAllListeners",
		"off",
		"addListener",
		"setMaxListeners",
		"user",
		"code",
		"angle",
		"direction",
		"target",
		"from_x",
		"from_y",
		"going_x",
		"going_y",
		"moving",
		"vx",
		"vy",
		"move_num",
		"a_angle",
		"a_direction",
		"focus",
		"ms_walk",
		"last_stop",
		"last_walking",
		"party",
		"ref_speed",
		"tp",
		"rtexture",
		"appearing",
		"filter_list",
		"filter_alphaf",
		"disappearing"
	],
	"read_only": [
		"x",
		"y",
		"real_x",
		"real_y",
		"from_x",
		"from_y",
		"going_x",
		"going_y",
		"moving",
		"target",
		"vx",
		"vy",
		"move_num",
		"attack",
		"speed",
		"hp",
		"mp",
		"xp",
		"max_hp",
		"max_mp",
		"range",
		"level",
		"rip",
		"s",
		"c",
		"in",
		"map",
		"stand",
		"items",
		"slots",
		"on",
		"once"
	],
	"proxy_character": true,
	"alpha": 1,
	"visible": true,
	"cskin": "11",
	"i": 1,
	"j": 1,
	"skin": "mbody2b",
	"stype": "full",
	"updates": 378637,
	"cscale": 2,
	"in": "main",
	"map": "main",
	"hp": 6865,
	"max_hp": 6865,
	"mp": 756,
	"max_mp": 1390,
	"xp": 208157683,
	"attack": 745,
	"heal": 0,
	"frequency": 1.2640111278525912,
	"speed": 76,
	"range": 204,
	"armor": 232,
	"resistance": 228,
	"level": 71,
	"rip": false,
	"afk": false,
	"s": {
		"rspeed": {
			"ms": 1023778,
			"f": "RisingVanir"
		},
		"halloween2": {
			"ms": 27190105
		},
		"mluck": {
			"ms": 3350235,
			"f": "VendorGuy",
			"strong": true
		}
	},
	"c": {},
	"q": {},
	"age": 184,
	"pdps": 336455.8450356324,
	"id": "couplaGrapes",
	"cid": 83311,
	"cx": {
		"hair": "hairdo206",
		"head": "fmakeup03",
		"makeup": "facemakeup02"
	},
	"slots": {
		"ring1": {
			"name": "suckerpunch",
			"level": 0
		},
		"ring2": {
			"name": "suckerpunch",
			"level": 0
		},
		"earring1": {
			"level": 1,
			"name": "dexearring"
		},
		"earring2": {
			"level": 1,
			"name": "intearring"
		},
		"belt": {
			"level": 2,
			"name": "dexbelt"
		},
		"mainhand": {
			"name": "hbow",
			"level": 7
		},
		"offhand": {
			"level": 8,
			"name": "quiver"
		},
		"helmet": {
			"stat_type": "dex",
			"name": "xmashat",
			"level": 7
		},
		"chest": {
			"level": 8,
			"stat_type": "dex",
			"name": "epyjamas"
		},
		"pants": {
			"acc": 289206,
			"name": "xmaspants",
			"level": 6,
			"ach": "gooped",
			"stat_type": "dex"
		},
		"shoes": {
			"level": 8,
			"stat_type": "dex",
			"name": "xmasshoes"
		},
		"gloves": {
			"level": 7,
			"stat_type": "dex",
			"name": "mittens"
		},
		"amulet": {
			"name": "skullamulet",
			"level": 2
		},
		"orb": {
			"level": 0,
			"name": "test_orb"
		},
		"elixir": null,
		"cape": {
			"level": 5,
			"stat_type": "dex",
			"name": "ecape"
		}
	},
	"ctype": "ranger",
	"owner": "5711289004851200",
	"int": 48,
	"str": 34,
	"dex": 223,
	"vit": 50,
	"for": 12,
	"mp_cost": 37,
	"mp_reduction": 0,
	"max_xp": 350000000,
	"goldm": 1.105,
	"xpm": 1.27,
	"luckm": 1.28,
	"isize": 42,
	"esize": 31,
	"gold": 2523147,
	"cash": 0,
	"targets": 0,
	"m": 34,
	"evasion": 0.5,
	"miss": 0,
	"reflection": 0,
	"lifesteal": 4,
	"manasteal": 0,
	"rpiercing": 38,
	"apiercing": 153,
	"crit": 4,
	"critdamage": 0,
	"dreturn": 0,
	"tax": 0.02,
	"xrange": 25,
	"pnresistance": 10,
	"firesistance": 20,
	"fzresistance": 20,
	"phresistance": 0,
	"stresistance": 0,
	"incdmgamp": 0,
	"stun": 0,
	"blast": 0,
	"explosion": 0,
	"courage": 2,
	"mcourage": 2,
	"pcourage": 2,
	"fear": 0,
	"items": [
		{
			"name": "tracker"
		},
		{
			"q": 5716,
			"name": "hpot1"
		},
		{
			"q": 9964,
			"name": "hpot1"
		},
		{
			"q": 7212,
			"name": "mpot1"
		},
		{
			"name": "ringsj",
			"level": 0
		},
		{
			"name": "wcap",
			"level": 0
		},
		{
			"name": "seashell",
			"q": 2
		},
		{
			"name": "crabclaw",
			"q": 1
		},
		{
			"name": "candy0",
			"q": 1
		},
		{
			"name": "gem0",
			"q": 1
		},
		{
			"name": "ringsj",
			"level": 0
		},
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null,
		null
	],
	"cc": 6,
	"ipass": "ET9LZmBm781S",
	"home": "USI",
	"friends": [
		"5069421845938176",
		"5690245074386944"
	],
	"acx": {},
	"xcx": [
		"makeup105",
		"makeup117",
		"mmakeup00",
		"fmakeup01",
		"fmakeup02",
		"fmakeup03",
		"marmor5a",
		"hairdo106",
		"mbody2b",
		"hairdo206",
		"facemakeup02"
	],
	"emx": {},
	"pzazz": 0.5,
	"last_ms": "2022-10-12T06:08:53.363Z",
	"name": "couplaGrapes",
	"walking": null,
	"fx": {
		"aaa": null,
		"attack": [
			"2022-10-12T06:08:52.962Z",
			0
		]
	},
	"emblems": {},
	"real_alpha": 1,
	"real_x": -1166.3100928140552,
	"real_y": 478.627440332755,
	"type": "character",
	"me": 1,
	"base": {
		"h": 8,
		"v": 7,
		"vn": 2
	},
	"awidth": 27,
	"aheight": 34,
	"explanation": "Hey Adventurer! This is your very own character that is a PIXI.Sprite Object. Adventure Land uses PIXI to draw things. You can learn more about it: https://www.pixijs.com/ and draw your own stuff via CODE! (Technical) Since your character is a special object, it doesn't get drawn like other entities, therefore your real character object has static x and y values. The character object in Code is an Object that mimics and extends your actual character Object. It's kinda complicated, but the only difference is that your real character object has different x and y values.",
	"ping": 130.75,
	"vision": [
		700,
		500
	],
	"ntag_cache": "couplaGrapes|undefined|false|false|false|false|false|false|true",
	"name_tag": {
		"x": 0,
		"y": 0,
		"width": 1,
		"height": 1,
		"alpha": 1,
		"visible": true,
		"zy": -999999999999999,
		"name": null
	},
	"last_fear": 0,
	"stats": {
		"str": 34,
		"dex": 223,
		"int": 48,
		"vit": 50,
		"for": 12
	},
	"listeners": [
		{
			"id": "oB7TKxe3zb2anBL7gpOxaf7Oo6Nmbz",
			"event": "stacked"
		},
		{
			"id": "gs0A4xcJrbCJWJw3QF0VBd0Nrf1iVC",
			"event": "death"
		},
		{
			"id": "HnEDHgGeWWCJu6iIVAiyiG80I4RTm0",
			"event": "cm"
		},
		{
			"id": "r2F59BE4SFsJ7TvUTsf5vA6lk5pyUQ",
			"event": "incoming"
		}
	],
	"bot": "",
	"code": true,
	"angle": -143.719976084409,
	"direction": 1,
	"target": "2530311",
	"from_x": -1279.1875622601283,
	"from_y": 511.40891038074864,
	"going_x": -1166.3100928140552,
	"going_y": 478.627440332755,
	"moving": false,
	"vx": 0,
	"vy": 0,
	"move_num": 22147093,
	"a_angle": -143.719976084409,
	"a_direction": 1,
	"focus": null,
	"ms_walk": "2022-10-12T06:08:53.113Z",
	"last_stop": "2022-10-12T06:08:53.157Z",
	"last_walking": 24838,
	"party": "couplaGrapes",
	"ref_speed": 76,
	"tp": 0,
	"appearing": false
}